apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
    spec:
      containers:
      - image: hossamdash/techtrends:latest
        imagePullPolicy: IfNotPresent
        name: techtrends
        resources: 
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111